__title__ = 'kimai-cli'
__description__ = 'A command line interface for the Kimai time tracking software.'
__url__ = 'https://github.com/wycomco/kimai-cli'
__version__ = '0.6.1'
__author__ = 'Kai Sassnowski'
__author_email__ = 'me@kai-sassnowski.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2018 Kai Sassnowski'
